metadata:
  labels:
    app: elm-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elm-app
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: 
              memory: 
            limits:
              cpu: 
              memory: 512Mi
          env:
          - name: JAVA_DIAGNOSTICS
            value: true
