apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: elm-service
    group: sa.elm.webservice
    provider: fabric8
    version: 1.0.0-SNAPSHOT
  name: elm-service-s2i
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: elm-service:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jboss-fuse70-java-openshift:1.0
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0
