apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"BuildConfig","metadata":{"annotations":{},"creationTimestamp":null,"name":"fis-sample-pipeline","namespace":"jenkins-ci"},"spec":{"nodeSelector":{},"output":{},"postCommit":{},"resources":{},"runPolicy":"Serial","source":{"git":{"ref":"master","uri":"https://github.com/rahmed-rh/elm-service.git"},"type":"Git"},"strategy":{"jenkinsPipelineStrategy":{"jenkinsfilePath":"Jenkinsfile"},"type":"JenkinsPipeline"},"triggers":[]},"status":{"lastVersion":0}}
  creationTimestamp: null
  name: fis-sample-pipeline
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: elm_preprod
      uri: https://bitbucket.elm.sa/scm/sam/elm-sample-openshift.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers: []
status:
  lastVersion: 0
